### PR TITLE
Created structure for the app, deleted _ in files, edited config for webpack for React-router

### PR DESCRIPTION
**Pull request by vvvjo**

### CODE REVIEW

**Comment by wunderg** [comment]
:+1:

**Comment by wunderg** [comment]
:+1:

**Comment by delphinefoo** [comment]
:+1:

**Comment by vvvjo** [comment]
:100:

**Comment by stinkyfruit** [comment]
:+1:

**Comment by wunderg** [comment]
:+1:

**Comment by vvvjo** [comment]
Closed PR. I need to do more fixes.

**Pull request closed without merging**
