### PR TITLE
Created Featured events cards, added banner image, and search bar to Landing Page

### PR DESCRIPTION
**Pull request by vvvjo**

### CODE REVIEW

**Comment by wunderg** [comment]
Vincent, I see you importing bootstrap into the index.html, from my previous project it was interfering with materialize css

**Comment by vvvjo** [comment]
Yea, since I was more familiar with Bootstrap's Grid and Row system I decided to mix them together. I will in the future just try to use MaterializeCSS grid system as much as I can.

**Comment by delphinefoo** [comment]
Let's stick to just one css framework, materialize. Vincent, would you mind pushing this back up when you've deleted bootstrap and styled the card grid with Materialize?

**Comment by wunderg** [comment]
Yeah, I think so as well. We should stick with one css framework

**Comment by wunderg** [comment]
maybe it wont be noticeable at first but at some point you will name your class and both libraries will have it and half of your day is gone

**Comment by wunderg** [comment]
Materialize has same grid and row system by the way, in my opinion it even easier then bootstrap

**Pull request closed without merging**
